# Generated by Django 6.0.4 on 2026-05-13 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetallePrestamo',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_devolucion_prevista', models.DateField()),
                ('estado', models.CharField(default='Pendiente', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('codigo_devolucion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_devolucion', models.DateField(auto_now_add=True)),
                ('hora_devolucion', models.TimeField(auto_now_add=True)),
                ('observaciones_devolucion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElementoDeportivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_maquina', models.CharField(max_length=100, verbose_name='Tipo de Máquina/Elemento')),
                ('cantidad_total', models.IntegerField(default=1)),
                ('estado_general', models.CharField(default='Buen estado', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('codigo_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('hora_prestamo', models.TimeField(auto_now_add=True)),
                ('dias_prestamo', models.IntegerField(default=1)),
                ('estado_prestamo', models.CharField(default='Activo', max_length=30)),
                ('observacion_prestamo', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('codigo_reserva', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_reserva', models.DateField()),
                ('hora_reserva', models.TimeField()),
                ('tiempo_permanencia', models.IntegerField(help_text='Duración en minutos')),
                ('estado_reserva', models.CharField(default='Pendiente', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('codigo_revision', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_novedad', models.CharField(max_length=100)),
                ('descripcion_detallada', models.TextField(blank=True)),
                ('estado_resolucion', models.CharField(default='Pendiente', max_length=30)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('codigo_sancion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_sancion', models.CharField(max_length=100)),
                ('fecha_inicio_sancion', models.DateField()),
                ('fecha_fin_sancion', models.DateField()),
                ('estado_sancion', models.CharField(default='Activa', max_length=30)),
                ('descripcion_sancion', models.TextField(blank=True)),
            ],
        ),
    ]
