# Generated by Django 6.0.4 on 2026-05-15 21:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ElementoDeportivo',
            fields=[
                ('codigo_elemento', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='elementos/')),
                ('nombre_elemento', models.CharField(max_length=100)),
                ('cantidad_total', models.IntegerField(default=0)),
                ('estado_general', models.CharField(max_length=50)),
                ('fecha_adquisicion', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('usuario_responsable', models.ForeignKey(blank=True, limit_choices_to={'is_staff': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='elementos_a_cargo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('codigo_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('hora_prestamo', models.TimeField(auto_now_add=True)),
                ('dias_prestamo', models.IntegerField(default=1)),
                ('dia_devolucion', models.DateField()),
                ('cantidad_prestada', models.IntegerField(default=1)),
                ('estado_prestamo', models.CharField(default='Activo', max_length=30)),
                ('observacion_prestamo', models.TextField(blank=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prestamos_realizados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('codigo_devolucion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_devuelta', models.IntegerField(default=1)),
                ('fecha_devolucion', models.DateField()),
                ('hora_devolucion', models.TimeField()),
                ('tiene_novedad', models.BooleanField(default=False)),
                ('estado_elemento_devolucion', models.CharField(max_length=50)),
                ('tipo_novedad_devolucion', models.CharField(blank=True, max_length=100)),
                ('observaciones_devolucion', models.TextField(blank=True)),
                ('dias_retraso', models.IntegerField(default=0)),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devoluciones', to='inventario.prestamo')),
            ],
        ),
        migrations.CreateModel(
            name='DetallePrestamo',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_devolucion', models.DateField()),
                ('estado', models.CharField(default='Pendiente', max_length=30)),
                ('prestamos_usuarios_aprendiz', models.CharField(blank=True, max_length=100)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.elementodeportivo')),
                ('prestamo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='inventario.prestamo')),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('codigo_revision', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_novedad', models.CharField(max_length=100)),
                ('descripcion_detallada', models.TextField(blank=True)),
                ('estado_resolucion', models.CharField(default='Pendiente', max_length=30)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
                ('devolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='revisiones', to='inventario.devolucion')),
            ],
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('codigo_sancion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_sancion', models.CharField(max_length=100)),
                ('fecha_inicio_sancion', models.DateField()),
                ('fecha_fin_sancion', models.DateField()),
                ('estado_sancion', models.CharField(default='Activa', max_length=30)),
                ('descripcion_sancion', models.TextField(blank=True)),
                ('devolucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sanciones', to='inventario.devolucion')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sanciones', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
