# Generated by Django 6.0.3 on 2026-05-08 19:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Devolucion',
            fields=[
                ('codigo_devolucion', models.AutoField(primary_key=True, serialize=False)),
                ('cantidad_devuelta', models.IntegerField(default=1)),
                ('fecha_devolucion', models.DateField()),
                ('hora_devolucion', models.TimeField()),
                ('tiene_novedad', models.BooleanField(default=False)),
                ('estado_elemento_devolucion', models.CharField(max_length=50)),
                ('tipo_novedad_devolucion', models.CharField(blank=True, max_length=100)),
                ('observaciones_devolucion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='ElementoDeportivo',
            fields=[
                ('codigo_elemento', models.AutoField(primary_key=True, serialize=False)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='elementos/')),
                ('tipo_maquina', models.CharField(max_length=100)),
                ('cantidad_total', models.IntegerField(default=0)),
                ('estado_general', models.CharField(max_length=50)),
                ('fecha_adquisicion', models.DateField()),
                ('descripcion', models.TextField(blank=True)),
                ('docente_responsable', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Revision',
            fields=[
                ('codigo_revision', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_revision', models.CharField(max_length=100)),
                ('revision_detallada', models.TextField(blank=True)),
                ('estado_resolucion', models.CharField(default='Pendiente', max_length=30)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sancion',
            fields=[
                ('codigo_sancion', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_sancion', models.CharField(max_length=100)),
                ('fecha_inicio_sancion', models.DateField()),
                ('fecha_fin_sancion', models.DateField()),
                ('estado_sancion', models.CharField(default='Activa', max_length=30)),
                ('descripcion_sancion', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='DetallePrestamo',
            fields=[
                ('id_detalle', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_devolucion', models.DateField()),
                ('estado', models.CharField(default='Pendiente', max_length=30)),
                ('prestamos_usuarios_aprendiz', models.CharField(blank=True, max_length=100)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventario.elementodeportivo')),
            ],
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('codigo_prestamo', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_prestamo', models.DateField(auto_now_add=True)),
                ('hora_prestamo', models.TimeField(auto_now_add=True)),
                ('dias_prestamo', models.IntegerField(default=1)),
                ('fecha_devolucion', models.DateField()),
                ('cantidad_prestada', models.IntegerField(default=1)),
                ('estado_prestamo', models.CharField(default='Activo', max_length=30)),
                ('observacion_prestamo', models.TextField(blank=True)),
                ('elemento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prestamos', to='inventario.elementodeportivo')),
            ],
        ),
    ]
