# Generated by Django 6.0.3 on 2026-04-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elementodeportivo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='elementos/'),
        ),
    ]
