# Generated by Django 6.0.4 on 2026-05-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FechaIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('habilitada', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Fecha de Ingreso',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='GimnasioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('abierta', 'Sala Abierta'), ('cerrada', 'Sala Cerrada'), ('mantenimiento', 'Mantenimiento')], default='abierta', max_length=20)),
                ('dias_habilitados', models.JSONField(default=list)),
                ('horario_apertura', models.TimeField(default='07:00')),
                ('horario_cierre', models.TimeField(default='17:00')),
                ('capacidad_maxima', models.PositiveIntegerField(default=40)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuración del Gimnasio',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('codigo_registro', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_entrada', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('tiempo_permanencia', models.IntegerField(default=60, help_text='Tiempo en minutos')),
                ('hora_salida', models.TimeField()),
                ('fecha_salida', models.DateField()),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
            ],
        ),
    ]
