# Generated by Django 6.0.3 on 2026-04-29 20:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('codigo_entrenamiento', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('disciplina', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='GimnasioConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('abierta', 'Sala Abierta'), ('cerrada', 'Sala Cerrada'), ('mantenimiento', 'Mantenimiento')], default='abierta', max_length=20)),
                ('dias_habilitados', models.JSONField(default=list)),
                ('horario_apertura', models.TimeField(default='07:00')),
                ('horario_cierre', models.TimeField(default='17:00')),
                ('capacidad_maxima', models.PositiveIntegerField(default=40)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuración del Gimnasio',
            },
        ),
        migrations.CreateModel(
            name='FechaIngreso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(blank=True, max_length=200)),
                ('habilitada', models.BooleanField(default=True)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fechas', to='gimnasio.gimnasioconfig')),
            ],
            options={
                'verbose_name': 'Fecha de Ingreso',
                'ordering': ['fecha'],
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('codigo_registro', models.AutoField(primary_key=True, serialize=False)),
                ('usuario_solicitante', models.CharField(max_length=100)),
                ('hora_prestamo', models.TimeField()),
                ('fecha_entrada', models.DateField()),
                ('hora_entrada', models.TimeField()),
                ('fecha_permanencia', models.DateField()),
                ('hora_salida', models.TimeField()),
                ('fecha_salida', models.DateField()),
                ('estado', models.CharField(default='Pendiente', max_length=20)),
                ('entrenamiento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservas', to='gimnasio.entrenamiento')),
            ],
        ),
    ]
