# Generated by Django 6.0.4 on 2026-05-25 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoIntercentros',
            fields=[
                ('codigo_equipo_centro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('disciplina', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TorneoIntercentros',
            fields=[
                ('codigo_torneo_centro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_torneo', models.CharField(max_length=100)),
                ('fecha_torneo', models.DateField()),
                ('lugar', models.CharField(max_length=100)),
                ('disciplina', models.CharField(max_length=50)),
                ('estado', models.CharField(default='Activo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='SeleccionadoSena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=50)),
                ('fecha_seleccion', models.DateField(help_text='Fecha en que se define la selección')),
                ('capacidad', models.IntegerField(default=10, help_text='Número máximo de seleccionados')),
                ('estado_seleccion', models.CharField(choices=[('en_proceso', 'En proceso'), ('definida', 'Definida'), ('cerrada', 'Cerrada')], default='en_proceso', max_length=30)),
                ('fecha_torneo', models.DateField(blank=True, null=True)),
                ('sede', models.CharField(blank=True, max_length=100)),
                ('hora_torneo', models.TimeField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('Activo', 'Activo'), ('Inactivo', 'Inactivo')], default='Activo', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('torneo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selecciones', to='intercentros.torneointercentros')),
            ],
            options={
                'verbose_name': 'Selección Sena',
                'verbose_name_plural': 'Selecciones Sena',
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='Resultado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partidos_jugados', models.PositiveIntegerField(default=0)),
                ('partidos_ganados', models.PositiveIntegerField(default=0)),
                ('partidos_empatados', models.PositiveIntegerField(default=0)),
                ('partidos_perdidos', models.PositiveIntegerField(default=0)),
                ('goles_favor', models.IntegerField(default=0)),
                ('goles_contra', models.IntegerField(default=0)),
                ('puntos', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercentros.equipointercentros')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercentros.torneointercentros')),
            ],
            options={
                'verbose_name': 'Resultado / Tabla de Posiciones',
            },
        ),
        migrations.CreateModel(
            name='Postulacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('ficha', models.CharField(blank=True, max_length=20)),
                ('programa_formacion', models.CharField(blank=True, max_length=150)),
                ('disciplina', models.CharField(max_length=50)),
                ('fecha_postulacion', models.DateTimeField(auto_now_add=True)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postulaciones', to='intercentros.torneointercentros')),
            ],
            options={
                'unique_together': {('torneo', 'numero_documento')},
            },
        ),
        migrations.CreateModel(
            name='ParticipacionIntercentros',
            fields=[
                ('codigo_participacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_juego', models.DateField()),
                ('puntaje', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercentros.equipointercentros')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercentros.torneointercentros')),
            ],
        ),
        migrations.AddField(
            model_name='equipointercentros',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='intercentros.torneointercentros'),
        ),
        migrations.CreateModel(
            name='Entrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('lugar', models.CharField(blank=True, max_length=100)),
                ('observacion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('torneo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrenamientos', to='intercentros.torneointercentros')),
            ],
        ),
        migrations.CreateModel(
            name='Clasificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posicion', models.PositiveIntegerField()),
                ('estado_clasificacion', models.CharField(default='En competencia', max_length=50)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercentros.equipointercentros')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercentros.torneointercentros')),
            ],
            options={
                'verbose_name_plural': 'Clasificaciones',
            },
        ),
        migrations.CreateModel(
            name='Aviso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('cuerpo', models.TextField()),
                ('tipo', models.CharField(choices=[('info', 'Información'), ('alerta', 'Alerta'), ('result', 'Resultado')], default='info', max_length=10)),
                ('disciplina', models.CharField(blank=True, help_text='Dejar en blanco para avisos generales', max_length=50)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('torneo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avisos', to='intercentros.torneointercentros')),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='AsistenciaEntrenamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20)),
                ('nombres', models.CharField(blank=True, max_length=100)),
                ('apellidos', models.CharField(blank=True, max_length=100)),
                ('ficha', models.CharField(blank=True, max_length=20)),
                ('confirmado_en', models.DateTimeField(auto_now_add=True)),
                ('entrenamiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='intercentros.entrenamiento')),
            ],
            options={
                'verbose_name': 'Asistencia a Entrenamiento',
                'verbose_name_plural': 'Asistencias a Entrenamientos',
                'ordering': ['nombres', 'apellidos'],
                'unique_together': {('entrenamiento', 'numero_documento')},
            },
        ),
        migrations.CreateModel(
            name='MiembroSeleccionado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_documento', models.CharField(max_length=20)),
                ('nombres', models.CharField(max_length=100)),
                ('apellidos', models.CharField(max_length=100)),
                ('ficha', models.CharField(blank=True, max_length=20)),
                ('programa_formacion', models.CharField(blank=True, max_length=150)),
                ('disciplina', models.CharField(max_length=50)),
                ('seleccionado_en', models.DateTimeField(auto_now_add=True)),
                ('postulacion', models.ForeignKey(blank=True, help_text='Postulación original del aprendiz (referencia)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='selecciones_asignadas', to='intercentros.postulacion')),
                ('seleccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='miembros', to='intercentros.seleccionadosena')),
            ],
            options={
                'verbose_name': 'Miembro Seleccionado',
                'verbose_name_plural': 'Miembros Seleccionados',
                'ordering': ['apellidos', 'nombres'],
                'unique_together': {('seleccion', 'numero_documento')},
            },
        ),
    ]
