# Generated by Django 6.0.3 on 2026-03-25 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipoIntercentros',
            fields=[
                ('codigo_equipo_centro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('disciplina', models.CharField(max_length=50)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SeleccionadorSena',
            fields=[
                ('codigo_seleccionador', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_seleccion', models.CharField(max_length=100)),
                ('disciplina', models.CharField(max_length=50)),
                ('fecha_seleccion', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='TorneoIntercentros',
            fields=[
                ('codigo_torneo_centro', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_torneo', models.CharField(max_length=100)),
                ('fecha_torneo', models.DateField()),
                ('lugar', models.CharField(max_length=100)),
                ('disciplina', models.CharField(max_length=50)),
                ('estado', models.CharField(default='Activo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ParticipacionIntercentros',
            fields=[
                ('codigo_participacion', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_juego', models.DateField()),
                ('puntaje', models.IntegerField(default=0)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercentros.equipointercentros')),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='intercentros.torneointercentros')),
            ],
        ),
        migrations.AddField(
            model_name='equipointercentros',
            name='torneo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='intercentros.torneointercentros'),
        ),
    ]
