# Generated by Django 6.0.4 on 2026-05-25 18:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_disciplina', models.CharField(max_length=50, unique=True)),
                ('icono', models.CharField(default='fa-medal', max_length=60)),
                ('reglas', models.TextField(blank=True, default='')),
                ('tipo_marcador', models.CharField(choices=[('goles', 'Goles (Fútbol, Fútsal, etc.)'), ('puntos', 'Puntos (Baloncesto, Voleibol americano)'), ('sets', 'Sets (Voleibol, Pimpón, Bádminton)')], default='goles', help_text='Define cómo se registra el resultado de cada partido', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GrupoInterfichas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_grupo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='JugadorEquipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='PartidoInterfichas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fase', models.CharField(choices=[('grupo', 'Fase de Grupos'), ('cuartos', 'Cuartos de Final'), ('semifinal', 'Semifinal'), ('final', 'Final')], default='grupo', max_length=20)),
                ('fecha_partido', models.DateField(blank=True, null=True)),
                ('hora_partido', models.TimeField(blank=True, null=True)),
                ('goles_local', models.IntegerField(blank=True, null=True)),
                ('goles_visitante', models.IntegerField(blank=True, null=True)),
                ('sets_local', models.JSONField(blank=True, null=True)),
                ('sets_visitante', models.JSONField(blank=True, null=True)),
                ('jugado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='ResultadoTorneo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_cierre', models.DateTimeField(auto_now_add=True)),
                ('archivado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TorneoInterfichas',
            fields=[
                ('codigo_torneo_fichas', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_torneo', models.CharField(max_length=100)),
                ('fecha_torneo_fichas', models.DateField()),
                ('horario_torneo_fichas', models.TimeField(default='08:00')),
                ('lugar', models.CharField(max_length=100)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipoInterfichas',
            fields=[
                ('codigo_equipo_interfichas', models.AutoField(primary_key=True, serialize=False)),
                ('ficha', models.IntegerField()),
                ('programa', models.CharField(max_length=150)),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('capitan', models.CharField(max_length=100)),
                ('fecha_inscripcion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(default='Inscrito', max_length=20)),
                ('disciplina', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='interfichas.disciplina')),
            ],
        ),
    ]
