# Generated by Django 6.0.3 on 2026-03-25 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TorneoInterfichas',
            fields=[
                ('codigo_torneo_fichas', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_torneo', models.CharField(max_length=100)),
                ('fecha_torneo_fichas', models.DateField()),
                ('horario_torneo_fichas', models.TimeField()),
                ('lugar', models.CharField(max_length=100)),
                ('disciplina', models.CharField(max_length=50)),
                ('estado', models.CharField(default='Activo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='EquipoInterfichas',
            fields=[
                ('codigo_equipo_interfichas', models.AutoField(primary_key=True, serialize=False)),
                ('ficha', models.IntegerField()),
                ('nombre_equipo', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('estado', models.CharField(default='Inscrito', max_length=20)),
                ('disciplina', models.CharField(max_length=50)),
                ('torneo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipos', to='interfichas.torneointerfichas')),
            ],
        ),
    ]
