# Generated by Django 6.0.3 on 2026-04-07 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('interfichas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Disciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_disciplina', models.CharField(max_length=50, unique=True)),
            ],
        ),
    ]
